name: atomsim-atombones
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: atomsim-atombones
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          path: riscv-atom
          
      - name: Install Verilator
        run:
          sudo apt-get install verilator
    
      - name: Set RVATOM directory
        run: 
          echo "RVATOM=$GITHUB_WORKSPACE/riscv-atom" >> $GITHUB_ENV

      - name: Build AtomSim for AtomBones Target
        run:
          cd riscv-atom; chmod +x install_toolchain.sh; ./install_toolchain.sh; make Target=hydrogensoc lib
